package projet.suiviapprenti.beans;
// Generated 23 f�vr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;



import org.codehaus.jackson.map.annotate.JsonView;

import projet.suiviapprenti.JSON.JSONViews;


/**
 * Apprenti generated by hbm2java
 */

public class Apprenti implements java.io.Serializable {

	private Integer idApprenti;
	@JsonView(JSONViews.InfoProfil.class)	private Classe classe;
	@JsonView(JSONViews.InfoProfil.class)   private Coordonnees coordonnees;
	@JsonView(JSONViews.InfoProfil.class)   private Entreprise entreprise;
	@JsonView(JSONViews.InfoProfil.class)	private String nom;
	@JsonView(JSONViews.InfoProfil.class)	private String prenom;
	@JsonView(JSONViews.InfoProfil.class)	private String sexe;
	@JsonView(JSONViews.InfoProfil.class)	private Date dateNaissance;
	@JsonView(JSONViews.InfoProfil.class)	private String lieuNaissance;
	@JsonView(JSONViews.InfoProfil.class)	private Date dateDebutContrat;
	@JsonView(JSONViews.InfoProfil.class)	private Date dateFinContrat;
	private String codeRfid;
	private String motDePasse;
	@JsonView(JSONViews.InfoProfil.class)	private String missionPrincipale;
	private Set<Cursusformation> cursusformations = new HashSet<Cursusformation>(0);
	private Set<ParcoursPostBts> parcoursPostBtses = new HashSet<ParcoursPostBts>(0);

	public Apprenti() {
	}

	public Apprenti(Classe classe, Coordonnees coordonnees, Entreprise entreprise, String nom, String prenom,
			String sexe, Date dateNaissance, String lieuNaissance, Date dateDebutContrat, Date dateFinContrat,
			String codeRfid, String motDePasse) {
		this.classe = classe;
		this.coordonnees = coordonnees;
		this.entreprise = entreprise;
		this.nom = nom;
		this.prenom = prenom;
		this.sexe = sexe;
		this.dateNaissance = dateNaissance;
		this.lieuNaissance = lieuNaissance;
		this.dateDebutContrat = dateDebutContrat;
		this.dateFinContrat = dateFinContrat;
		this.codeRfid = codeRfid;
		this.motDePasse = motDePasse;
	}

	public Apprenti(Classe classe, Coordonnees coordonnees, Entreprise entreprise, String nom, String prenom,
			String sexe, Date dateNaissance, String lieuNaissance, Date dateDebutContrat, Date dateFinContrat,
			String codeRfid, String motDePasse,	Set<Cursusformation> cursusformations,Set<ParcoursPostBts> parcoursPostBtses) {
		this.classe = classe;
		this.coordonnees = coordonnees;
		this.entreprise = entreprise;
		this.nom = nom;
		this.prenom = prenom;
		this.sexe = sexe;
		this.dateNaissance = dateNaissance;
		this.lieuNaissance = lieuNaissance;
		this.dateDebutContrat = dateDebutContrat;
		this.dateFinContrat = dateFinContrat;
		this.codeRfid = codeRfid;
		this.motDePasse = motDePasse;
		this.missionPrincipale = missionPrincipale;
		this.cursusformations = cursusformations;
		this.parcoursPostBtses = parcoursPostBtses;
	}


	public Integer getIdApprenti() {
		return this.idApprenti;
	}

	public void setIdApprenti(Integer idApprenti) {
		this.idApprenti = idApprenti;
	}

	public Classe getClasse() {
		return this.classe;
	}

	public void setClasse(Classe classe) {
		this.classe = classe;
	}


	public Coordonnees getCoordonnees() {
		return this.coordonnees;
	}

	public void setCoordonnees(Coordonnees coordonnees) {
		this.coordonnees = coordonnees;
	}

	public Entreprise getEntreprise() {
		return this.entreprise;
	}

	public void setEntreprise(Entreprise entreprise) {
		this.entreprise = entreprise;
	}


	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}


	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}


	public String getLieuNaissance() {
		return this.lieuNaissance;
	}

	public void setLieuNaissance(String lieuNaissance) {
		this.lieuNaissance = lieuNaissance;
	}


	public Date getDateDebutContrat() {
		return this.dateDebutContrat;
	}

	public void setDateDebutContrat(Date dateDebutContrat) {
		this.dateDebutContrat = dateDebutContrat;
	}


	public Date getDateFinContrat() {
		return this.dateFinContrat;
	}

	public void setDateFinContrat(Date dateFinContrat) {
		this.dateFinContrat = dateFinContrat;
	}


	public String getCodeRfid() {
		return this.codeRfid;
	}

	public void setCodeRfid(String codeRfid) {
		this.codeRfid = codeRfid;
	}


	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}


	public String getMissionPrincipale() {
		return this.missionPrincipale;
	}

	public void setMissionPrincipale(String missionPrincipale) {
		this.missionPrincipale = missionPrincipale;
	}



	public Set<Cursusformation> getCursusformations() {
		return this.cursusformations;
	}

	public void setCursusformations(Set<Cursusformation> cursusformations) {
		this.cursusformations = cursusformations;
	}

	public Set<ParcoursPostBts> getParcoursPostBtses() {
		return this.parcoursPostBtses;
	}

	public void setParcoursPostBtses(Set<ParcoursPostBts> parcoursPostBtses) {
		this.parcoursPostBtses = parcoursPostBtses;
	}

}
