package projet.suiviapprenti.beans;
// Generated 23 f�vr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.map.annotate.JsonView;

import projet.suiviapprenti.JSON.JSONViews;


/**
 * Coordonnees generated by hbm2java
 */

public class Coordonnees implements java.io.Serializable {

	private Integer idcoordonnees;
	@JsonView(JSONViews.InfoProfil.class) private String rue;
	@JsonView(JSONViews.InfoProfil.class) private String ville;
	@JsonView(JSONViews.InfoProfil.class) private String codePostal;
	@JsonView(JSONViews.InfoProfil.class) private String telephone;
	@JsonView(JSONViews.InfoProfil.class) private String mobile;
	@JsonView(JSONViews.InfoProfil.class) private String email;
	@JsonView(JSONViews.InfoProfil.class) private String site;
	private Set<Apprenti> apprentis = new HashSet<Apprenti>(0);
	private Set<Entreprise> entreprises = new HashSet<Entreprise>(0);

	public Coordonnees() {
	}

	public Coordonnees(String rue, String ville, String codePostal, String telephone, String mobile, String email,
			String site) {
		this.rue = rue;
		this.ville = ville;
		this.codePostal = codePostal;
		this.telephone = telephone;
		this.mobile = mobile;
		this.email = email;
		this.site = site;
	}

	public Coordonnees(String rue, String ville, String codePostal, String telephone, String mobile, String email,
			String site, Set<Apprenti> apprentis, Set<Entreprise> entreprises) {
		this.rue = rue;
		this.ville = ville;
		this.codePostal = codePostal;
		this.telephone = telephone;
		this.mobile = mobile;
		this.email = email;
		this.site = site;
		this.apprentis = apprentis;
		this.entreprises = entreprises;
	}


	public Integer getIdcoordonnees() {
		return this.idcoordonnees;
	}

	public void setIdcoordonnees(Integer idcoordonnees) {
		this.idcoordonnees = idcoordonnees;
	}

	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	public Set<Apprenti> getApprentis() {
		return this.apprentis;
	}

	public void setApprentis(Set<Apprenti> apprentis) {
		this.apprentis = apprentis;
	}

	public Set<Entreprise> getEntreprises() {
		return this.entreprises;
	}

	public void setEntreprises(Set<Entreprise> entreprises) {
		this.entreprises = entreprises;
	}

}
