package projet.suiviapprenti.beans;
// Generated 23 f�vr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Cursusformation generated by hbm2java
 */
public class Cursusformation implements java.io.Serializable {

	private Integer idcursusformation;
	private Apprenti apprenti;
	private String type;
	private Date annee;
	private String titreObtenu;
	private String titreComplement;

	public Cursusformation() {
	}

	public Cursusformation(Apprenti apprenti, String type, Date annee, String titreObtenu, String titreComplement) {
		this.apprenti = apprenti;
		this.type = type;
		this.annee = annee;
		this.titreObtenu = titreObtenu;
		this.titreComplement = titreComplement;
	}

	public Integer getIdcursusformation() {
		return this.idcursusformation;
	}

	public void setIdcursusformation(Integer idcursusformation) {
		this.idcursusformation = idcursusformation;
	}

	public Apprenti getApprenti() {
		return this.apprenti;
	}

	public void setApprenti(Apprenti apprenti) {
		this.apprenti = apprenti;
	}


	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getAnnee() {
		return this.annee;
	}

	public void setAnnee(Date annee) {
		this.annee = annee;
	}


	public String getTitreObtenu() {
		return this.titreObtenu;
	}

	public void setTitreObtenu(String titreObtenu) {
		this.titreObtenu = titreObtenu;
	}


	public String getTitreComplement() {
		return this.titreComplement;
	}

	public void setTitreComplement(String titreComplement) {
		this.titreComplement = titreComplement;
	}

}
